title: Bukurešť
country: Rumunsko
flag: flags/ro.svg
updated_by: 84a5061c-1f53-412f-9037-bfbdae1bb5fc
updated_at: 1683580579
blueprint: city
localizations:
  en:
    title: Bucharest
    country: Romania
    slug: bukurest
    updated_by: 84a5061c-1f53-412f-9037-bfbdae1bb5fc
    updated_at: 1680615703
