title: Londýn
country: 'Velká Británie'
flag: flags/gb.png
updated_by: 84a5061c-1f53-412f-9037-bfbdae1bb5fc
updated_at: 1680614783
blueprint: city
localizations:
  en:
    title: London
    country: 'Great Britain'
    slug: london
    updated_by: 84a5061c-1f53-412f-9037-bfbdae1bb5fc
    updated_at: 1680614812
